stages:
  scrape:
    cmd: python src/scraper.py
    params:
      - params.yaml:
        - scraper
    outs:
      - raw/messages:
          cache: true
          persist: true
      - raw/members:
          cache: true
          persist: true
      - raw/invite_links:
          cache: true
          persist: true
      - raw/media:
          cache: true
          persist: true

  analyze_store_status:
    cmd: python src/analyze_store_status.py
    deps:
      - raw/messages
      - raw/media
      - src/analyze_store_status.py
    outs:
      - processed/store_status:
          cache: true
          persist: true

  prepare_web_data:
    cmd: python src/prepare_web_data.py
    deps:
      - raw/members
      - raw/messages
      - processed/store_status/daily_status.jsonl
      - processed/store_status/user_attributions.json
      - src/prepare_web_data.py
    outs:
      - processed/web_data:
          cache: true
          persist: true
